"""add one to many

Revision ID: 0b3a2f0fd6c2
Revises: cb23047c8d3d
Create Date: 2025-01-15 10:12:19.396102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3a2f0fd6c2'
down_revision = 'cb23047c8d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('team_manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_manager_id'], ['team_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('team_manager')
    # ### end Alembic commands ###
